#!/usr/bin/env python3

sequences=['ATGCCCGGCCCGGC','GCGTGCTAGCAATACGATAAACCGG', 'ATATATATCGAT','ATGGGCCC']

for seq in sequences:
	length=len(seq)
	pos=sequences.index(seq)
	print(length, "\t",seq, "\t", pos)



